sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4'
  - '0.12'
  - '0.10'
before_install:
  # Prevent "tell me who you are" errors 
  - git config --global user.name "TravisCI"
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
script:
  - npm run test
  - npm run check-coverage
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
