  # File: jobs/build.yml

parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: git config --global user.email "example@example.com"
  - script: git config --global user.name "Example Git User"
  - script: npm install -g yarn
  - script: npm install
  - script: npm run build
  - script: npm test
  - ${{ if eq(parameters.sign, 'true') }}:
    - script: sign
